import type { Metadata } from 'next';
import { Inter, Roboto_Mono } from 'next/font/google';
import SessionProviderWrapper from '@/components/providers/SessionProviderWrapper';
import '../styles/globals.css';

const interFont = Inter({
	variable: '--font-inter',
	subsets: ['latin']
});

const robotoMonoFont = Roboto_Mono({
	variable: '--font-roboto-mono',
	subsets: ['latin']
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='en'>
			<body className={`${interFont.variable} ${robotoMonoFont.variable} antialiased`}>
				<SessionProviderWrapper>{children}</SessionProviderWrapper>
			</body>
		</html>
	);
}
