/**
 * Cloudflare Workers entry point.
 *
 * Wraps the worker generated by `opennextjs-cloudflare build` (`.open-next/worker.js`)
 * and adds a `scheduled` handler so Cloudflare Cron Triggers (see `triggers.crons` in
 * wrangler.jsonc) can run GET /api/cron/master with `Authorization: Bearer $CRON_SECRET`,
 * plus the cron expression and scheduled time that fired (the route picks jobs from them). The request is dispatched in-process through
 * the Next.js handler, so the route's own auth check stays the single gate.
 *
 * Pattern: https://opennext.js.org/cloudflare/howtos/custom-worker
 */

// @ts-ignore `.open-next/worker.js` is generated at build time
import { default as handler } from '../.open-next/worker.js';

interface Env {
	CRON_SECRET?: string;
	NEXTAUTH_URL?: string;
	[key: string]: unknown;
}

interface ExecutionContextLike {
	waitUntil(promise: Promise<unknown>): void;
	passThroughOnException(): void;
}

interface ScheduledControllerLike {
	cron: string;
	scheduledTime: number;
}

// Registered by src/lib/db.ts (in the Next.js bundle) once a request has used MongoDB.
const REQUEST_DB_REGISTRY = Symbol.for('pick5.requestDb');
type RequestDbRegistry = { has(key: object): boolean; close(key: object): Promise<void> };

/**
 * Runs the Next.js handler, then closes the request's MongoDB connection once the
 * response body has been fully sent (sockets can't be reused by later requests on
 * Workers, so leaving them open would only leak them).
 */
async function handle(request: Request, env: Env, ctx: ExecutionContextLike): Promise<Response> {
	const response: Response = await handler.fetch(request, env, ctx);
	const requestDb = (globalThis as Record<symbol, RequestDbRegistry | undefined>)[REQUEST_DB_REGISTRY];
	if (!requestDb?.has(ctx)) return response;

	if (!response.body) {
		ctx.waitUntil(requestDb.close(ctx));
		return response;
	}
	const { readable, writable } = new TransformStream();
	ctx.waitUntil(
		response.body
			.pipeTo(writable)
			.catch(() => {})
			.finally(() => requestDb.close(ctx))
	);
	return new Response(readable, response);
}

export default {
	fetch(request: Request, env: Env, ctx: ExecutionContextLike) {
		return handle(request, env, ctx);
	},

	async scheduled(controller: ScheduledControllerLike, env: Env, ctx: ExecutionContextLike) {
		if (!env.CRON_SECRET) {
			// The route would answer 401 anyway; fail loudly so it shows in the Cron Events log.
			throw new Error('[Cron] CRON_SECRET is not set; refusing to run /api/cron/master');
		}

		const origin = env.NEXTAUTH_URL || 'https://sportspick5.com';
		const request = new Request(new URL('/api/cron/master', origin), {
			method: 'GET',
			headers: {
				authorization: `Bearer ${env.CRON_SECRET}`,
				'x-cron-trigger': controller.cron,
				// The master route dispatches on the scheduled time, not on when the run started.
				'x-cron-scheduled-time': String(controller.scheduledTime)
			}
		});

		const response = await handle(request, env, ctx);
		const body = await response.text();
		console.log(`[Cron] ${controller.cron} -> /api/cron/master ${response.status}: ${body.slice(0, 2000)}`);
		if (!response.ok) {
			// Marks the invocation as failed in the dashboard's Cron Events.
			throw new Error(`[Cron] /api/cron/master returned ${response.status}`);
		}
	}
};

